- name: Restart OpenStack services
  hosts: "{{ target_hosts | default('all') }}"
  become: yes

  tasks:
    - name: Restart services
      import_role:
        name: openstack-operations
        tasks_from: restart_service.yml
