---
# Copyright 2021 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# Using two tasks with a boolean due to the ansible bug: https://github.com/ansible/ansible/issues/68364
- name: Collect the host and build the resulting host list
  set_fact:
    _hosts: "{{ _hosts|default([]) + [ hostvars[item].canonical_hostname ] }}"
  with_items: "{{ groups['ceph_nfs'] }}"
  when: tripleo_cephadm_fqdn | bool

- name: Collect the host and build the resulting host list
  set_fact:
    _hosts: "{{ _hosts|default([]) + [ hostvars[item].inventory_hostname ] }}"
  with_items: "{{ groups['ceph_nfs'] }}"
  when: not tripleo_cephadm_fqdn | bool

- name: Create the ganesha Daemon spec definition
  become: true
  ceph_mkspec:
    service_type: nfs
    apply: true
    hosts: "{{ _hosts }}"
    render_path: "{{ tripleo_cephadm_spec_home }}"
    spec:
      namespace: 'ganesha'
      pool: "{{ cephfs_data_pool }}"
  environment:
    CEPH_CONTAINER_IMAGE: "{{ tripleo_cephadm_container_ns + '/' + tripleo_cephadm_container_image + ':' + tripleo_cephadm_container_tag }}"
    CEPH_CONTAINER_BINARY: "{{ tripleo_cephadm_container_cli }}"
