---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Apply network configuration with os-net-config.
#

- name: Apply os-net-config configuration
  become: true
  block:
    - name: Render network_config
      no_log: "{{ tripleo_network_config_hide_sensitive_logs | bool }}"
      template:
        src: "{{ tripleo_network_config_script_path }}"
        dest: /etc/os-net-config/config.json
        mode: 0600
        backup: true
    - name: Run tripleo_os_net_config_module with network_config
      tripleo_os_net_config:
        config_file: /etc/os-net-config/config.json
        debug: "{{ tripleo_network_config_debug|bool }}"
        detailed_exit_codes: true
        safe_defaults: "{{ tripleo_network_config_safe_defaults | bool }}"
      async: "{{ tripleo_network_config_async_timeout }}"
      poll: "{{ tripleo_network_config_async_poll }}"
      register: NetworkConfig_result
