---

- name: Set node name fact
  set_fact:
    node_hostname: "{{ canonical_hostname }}"

- include_tasks: certificate.yml
  when:
    - generate_certs | bool

- include_tasks: netport.yml

- include_tasks: netinterface.yml

- name: making sure octavia common configuration directory exists
  file:
    path: "{{ octavia_confd_prefix }}/etc/octavia/conf.d/common"
    state: directory
    selevel: s0
    setype: svirt_sandbox_file_t
  become: true

- include_tasks: octavia.yml
